#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvscode monitor status"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name="vscode_protect"
  zdaemon status $service_name
}

run() {
  core $@
}

run $@
