#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvscode protect"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  vscode::protect
}

run() {
  core $@
}

run $@
