#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvscode watch"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  vscode::monitor
}

run() {
  core $@
}

run $@
